#Tasks of our roles
- name: Install EPEL repo
  package: name={{ item }} state=present
  when: ansible_distribution == "CentOS"
  loop:
    - epel-release
    - wget
    - git

- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py

- name: install python-pip
  command: python2.7 /tmp/get-pip.py

- name: Install docker python
  pip: name=docker-py

- name: create websites_files
  file:
    path: "/home/{{ ansible_user }}/website_files"
    state: directory

- name: copy websites_files
  copy:
    src: "/home/{{ my_ansible_user }}/ansible_training/website_files/"
    dest: "/home/{{ ansible_user }}/website_files"

- name: generate index.html file
  template:
    src: "index.html.j2"
    dest: "/home/{{ ansible_user }}/website_files/index.html"

- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd
    ports:
      - "80:80"
    volumes:
      - "/home/{{ ansible_user }}/website_files/:/usr/local/apache2/htdocs/:z"
